apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  no-env:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "testpropertymlcb: ${{ vars.testpropertymlcb }}"
          echo "testpropertymlcbONLYTOP: ${{ vars.testpropertymlcbONLYTOP }}"
  with-env:
    environment: mlcb
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "testpropertymlcb: ${{ vars.testpropertymlcb }}"
          echo "testpropertymlcbONLYTOP: ${{ vars.testpropertymlcbONLYTOP }}"
